from .app import db
from sqlalchemy_serializer import SerializerMixin

class Player(db.Model, SerializerMixin):
    id = db.Column(db.String(65), primary_key=True)
    year = db.Column(db.String(9))
    name= db.Column(db.String(50))
    team = db.Column(db.String(50))
    age = db.Column(db.Integer)
    pos = db.Column(db.String(10))
    gp = db.Column(db.Integer)
    g = db.Column(db.Integer)
    a = db.Column(db.Integer)
    p = db.Column(db.Integer)
    pim = db.Column(db.Integer)
    plusMin = db.Column(db.Integer)
    toi = db.Column(db.Float)
    toiEs = db.Column(db.Float)
    toiPp = db.Column(db.Float)
    toiSh = db.Column(db.Float)
    esg = db.Column(db.Integer)
    ppg = db.Column(db.Integer)
    shg = db.Column(db.Integer)
    gwg = db.Column(db.Integer)
    otg = db.Column(db.Integer)
    esa = db.Column(db.Integer)
    ppa = db.Column(db.Integer)
    sha = db.Column(db.Integer)
    gwa = db.Column(db.Integer)
    ota = db.Column(db.Integer)
    esp = db.Column(db.Integer)
    ppp = db.Column(db.Integer)
    shp = db.Column(db.Integer)
    gwp = db.Column(db.Integer)
    otp = db.Column(db.Integer)
    pppPercent = db.Column(db.Float)
    gPer60 = db.Column(db.Float)
    aPer60 = db.Column(db.Float)
    pPer60 = db.Column(db.Float)
    esgPer60 = db.Column(db.Float)
    esaPer60 = db.Column(db.Float)
    espPer60 = db.Column(db.Float)
    ppgPer60 = db.Column(db.Float)
    ppaPer60 = db.Column(db.Float)
    pppPer60 = db.Column(db.Float)
    gPerGp = db.Column(db.Float)
    aPerGp = db.Column(db.Float)
    pPerGp = db.Column(db.Float)
    shots = db.Column(db.Integer)
    shotPercent = db.Column(db.Float)
    hits = db.Column(db.Integer)
    bs = db.Column(db.Integer)
    fow = db.Column(db.Integer)
    fol = db.Column(db.Integer)
    foPercent = db.Column(db.Float)

class Goalie(db.Model, SerializerMixin):
    id = db.Column(db.String(65), primary_key=True)
    year = db.Column(db.String(9))
    name= db.Column(db.String(50))
    team = db.Column(db.String(50))
    age = db.Column(db.Integer)
    gp = db.Column(db.Integer)
    gaa = db.Column(db.Float)
    svPercent = db.Column(db.Float)
    w = db.Column(db.Integer)
    l = db.Column(db.Integer)
    so = db.Column(db.Integer)
    time = db.Column(db.Integer)
    g = db.Column(db.Integer)
    a = db.Column(db.Integer)
    p = db.Column(db.Integer)
    pim = db.Column(db.Integer)




